name: daman_task
description: "Creating a application where user able to login and add list of images to same name refrence key."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  cloud_firestore: ^5.4.2
  google_sign_in: ^6.2.1
  path_provider: ^2.1.2
  flutter_image_compress: ^2.3.0
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/svg/


  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/karla_light.ttf
          weight: 300
        - asset: assets/fonts/karla_regular.ttf
          weight: 400
        - asset: assets/fonts/karla_medium.ttf
          weight: 500
        - asset: assets/fonts/karla_semibold.ttf
          weight: 600
        - asset: assets/fonts/karla_bold.ttf
          weight: 700
        - asset: assets/fonts/karla_extra_bold.ttf
          weight: 800
